### PR TITLE
Updating mbed-os to mbed-os-5.3.4

### PR DESCRIPTION
**Pull request by adbridge**
Please test/merge this PR and then tag Master with mbed-os-5.3.4

### CODE REVIEW

**Comment by AlessandroA** [comment]
The failing test needs to be investigated with @mazimkhan. I suspect is the same issue being observed in #15.

**Comment by mazimkhan** [comment]
Created issue #17 to fix this.

**Comment by AlessandroA** [comment]
https://github.com/ARMmbed/mbed-os-example-uvisor-number-store/pull/15 should fix the outstanding issues. As soon as that is merged we can merge this one as well.

**Comment by AlessandroA** [comment]
retest uvisor

**Pull request merged**
