### PR TITLE
Minor improvements to the app

### PR DESCRIPTION
**Pull request by AlessandroA**
These improvements get us much closer to the addition of new targets to this app.

### CODE REVIEW

**Comment by AlessandroA** [comment]
retest uvisor

**Comment by AlessandroA** [comment]
retest uvisor

**Comment by mazimkhan** [comment]
Created issue #17 to fix this.

**Comment by AlessandroA** [comment]
retest uvisor

**Comment by Patater** [comment]
LGTM. Merge when CI passes.

**Comment by AlessandroA** [comment]
retest uvisor

**Comment by AlessandroA** [comment]
retest uvisor

**Pull request merged**
